#include "crypto.hpp"
#include "ipc.hpp"
#include <wincred.h>
#include <objbase.h>
#include <ntsecapi.h>
#include <iostream>
#include <fstream>
using namespace pu;using native::require;
template<class F>void rejected(F&& f){bool failed=false;try{f();}catch(...){failed=true;}require(failed,"Invalid vault input accepted");}
int wmain(int argc,wchar_t** argv){try{
  vault::Secret key(random(32));const std::wstring password=L"dummy-Password-For-Test-Only-42!";auto envelope=vault::seal(key.bytes,password,"delegate-aad");auto plain=vault::open(key.bytes,envelope,"delegate-aad");
  require(plain.bytes==Bytes(reinterpret_cast<const BYTE*>(password.data()),reinterpret_cast<const BYTE*>(password.data())+password.size()*2),"Password round trip mismatch");
  rejected([&]{vault::open(random(32),envelope,"delegate-aad");});rejected([&]{vault::open(key.bytes,envelope,"different-aad");});auto tampered=envelope;tampered["tag"]=b64url(random(16));rejected([&]{vault::open(key.bytes,tampered,"delegate-aad");});
  vault::Ephemeral phone,laptop,wrong;auto stored=vault::wrap(phone.jwk(),key.bytes);auto decrypted=phone.unwrap(b64url(stored));require(decrypted.bytes==key.bytes,"Phone RSA unwrap");auto release=vault::wrap(laptop.jwk(),decrypted.bytes);require(laptop.unwrap(b64url(release)).bytes==key.bytes,"One-time RSA release");rejected([&]{wrong.unwrap(b64url(release));});rejected([&]{laptop.unwrap(b64url(stored));});auto privateJwk=phone.jwk();privateJwk["d"]="private";rejected([&]{vault::wrap(privateJwk,key.bytes);});
  const auto name="vault-test-"+uuid();SigningKey identity(name,true);struct Delete{SigningKey& key;~Delete(){try{key.erase();}catch(...){}}} remove{identity};
  if(argc==2&&std::wstring(argv[1])==L"--machine"){SigningKey machine("vault-machine-test-"+uuid(),true,true);Delete clean{machine};auto p=message("vault-cancel","password-unlock");require(verify(machine.sign(p),machine.jwk(),"vault-cancel","password-unlock")==p,"Protected machine CNG key signing failed");}
  auto request=message("vault-unlock","password-unlock");request.update(Json{{"requestId",uuid()},{"expiresAt",epoch()+60}});const auto requestJws=identity.sign(request);auto reply=message("vault-response","password-unlock");reply.update(Json{{"requestId",request.at("requestId")},{"challengeHash",hash(requestJws)},{"decision","approve"},{"wrappedKey",b64url(release)}});
  require(vault::response(identity.sign(reply),identity.jwk(),request,requestJws,false).at("decision")=="approve","Vault response validation");auto bad=reply;bad["challengeHash"]=hash("wrong");rejected([&]{vault::response(identity.sign(bad),identity.jwk(),request,requestJws,false);});bad=reply;bad["password"]="secret";rejected([&]{vault::response(identity.sign(bad),identity.jwk(),request,requestJws,false);});auto expired=request;expired["expiresAt"]=epoch();rejected([&]{vault::response(identity.sign(reply),identity.jwk(),expired,requestJws,false);});
  native::Request q;q.operation=native::Operation::Poll;q.scenario=1;q.sessionId=1;CoCreateGuid(&q.operationId);wcscpy_s(q.sid.data(),q.sid.size(),L"S-1-5-21-1-2-3-1001");native::Response r;r.windowsSignInEnabled=1;r.sid=q.sid;r.operationId=q.operationId;r.state=native::State::ApprovedSignIn;require(native::valid(r,q),"Poll must contain no credential");r.proofSize=1;require(!native::valid(r,q),"Credential leaked in poll");q.operation=native::Operation::Claim;require(native::valid(r,q),"One-time Claim framing");r.proofSize=0;require(!native::valid(r,q),"Empty Claim accepted");
  for(DWORD scenario:{1u,2u}){vault::Secret packed(vault::pack(L"TEST\\dummy",plain.bytes,scenario));auto h=reinterpret_cast<KERB_INTERACTIVE_UNLOCK_LOGON*>(packed.bytes.data());require(h->Logon.MessageType==(scenario==1?KerbInteractiveLogon:KerbWorkstationUnlockLogon)&&h->LogonId.HighPart==0&&h->LogonId.LowPart==0,"Local unlock/logon structure");auto offset=reinterpret_cast<size_t>(h->Logon.Password.Buffer);require(offset+h->Logon.Password.Length==packed.bytes.size(),"Relative password bounds");std::wstring encrypted(reinterpret_cast<wchar_t*>(packed.bytes.data()+offset),h->Logon.Password.Length/2);wchar_t pw[257]{};DWORD ps=257;require(CredUnprotectW(TRUE,encrypted.data(),DWORD(encrypted.size()),pw,&ps),"OS credential unprotect failed");require(std::wstring(pw)==password,"OS protected password mismatch");SecureZeroMemory(pw,sizeof(pw));}
  {vault::Secret packed(vault::pack(L"MicrosoftAccount\\test@example.com",plain.bytes));wchar_t user[2048]{},domain[257]{},pw[2048]{};DWORD us=2048,ds=257,ps=2048;require(CredUnPackAuthenticationBufferW(CRED_PACK_PROTECTED_CREDENTIALS,packed.bytes.data(),DWORD(packed.bytes.size()),user,&us,domain,&ds,pw,&ps),"Microsoft account packing failed");require(us>1&&ps>1&&std::wstring(pw)!=password,"Online identity must use the OS marshaled credential format");DWORD count{};CredPackAuthenticationBufferW(CRED_PACK_PROTECTED_CREDENTIALS|CRED_PACK_ID_PROVIDER_CREDENTIALS,user,pw,nullptr,&count);require(GetLastError()==ERROR_INSUFFICIENT_BUFFER&&count<8192,"Online credential cannot be repacked");vault::Secret roundtrip{Bytes(count)};require(CredPackAuthenticationBufferW(CRED_PACK_PROTECTED_CREDENTIALS|CRED_PACK_ID_PROVIDER_CREDENTIALS,user,pw,roundtrip.bytes.data(),&count),"Online marshaled credential round trip");SecureZeroMemory(pw,sizeof(pw));}
  require(vault::negotiatePackage()!=ULONG(-1),"Built-in package lookup");
  if(argc==3&&std::wstring(argv[1])==L"--interop"){
    std::ifstream input(argv[2]);std::string text((std::istreambuf_iterator<char>(input)),{});auto j=parse(text);vault::rsaPublic(j.at("rsaJwk"));Json output{{"wrappedKey",b64url(vault::wrap(j.at("rsaJwk"),key.bytes))},{"envelope",envelope},{"aad","delegate-aad"}};std::ofstream file(std::filesystem::path(argv[2]).wstring()+L".windows.json");file<<output.dump();
  }
  std::cout<<"Vault tampering, RSA release, expiry, IPC and Windows credential packing checks passed\n";return 0;
}catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}}
