#include "crypto.hpp"
#include <wincred.h>
#define SECURITY_WIN32
#include <security.h>
#include <ntsecapi.h>
#include <algorithm>
namespace pu::vault {
using native::require;
namespace {
void ok(NTSTATUS s){require(s>=0,"Vault cryptography failed");}
struct Alg {BCRYPT_ALG_HANDLE h{};~Alg(){if(h)BCryptCloseAlgorithmProvider(h,0);}};
struct Key {BCRYPT_KEY_HANDLE h{};Key()=default;Key(const Key&)=delete;Key(Key&& other)noexcept:h(std::exchange(other.h,nullptr)){};~Key(){if(h)BCryptDestroyKey(h);}};
Key imported(const Json& j,BCRYPT_ALG_HANDLE alg){rsaPublic(j);auto n=unb64url(j.at("n")),e=unb64url(j.at("e"));Bytes blob(sizeof(BCRYPT_RSAKEY_BLOB)+e.size()+n.size());auto head=reinterpret_cast<BCRYPT_RSAKEY_BLOB*>(blob.data());*head={BCRYPT_RSAPUBLIC_MAGIC,2048,ULONG(e.size()),ULONG(n.size()),0,0};std::copy(e.begin(),e.end(),blob.begin()+sizeof(*head));std::copy(n.begin(),n.end(),blob.begin()+sizeof(*head)+e.size());Key k;ok(BCryptImportKeyPair(alg,nullptr,BCRYPT_RSAPUBLIC_BLOB,&k.h,blob.data(),ULONG(blob.size()),0));return k;}
Secret gcm(const Bytes& key,const Bytes& input,const Bytes& iv,Bytes& tag,const std::string& aad,bool encrypt){
  require(key.size()==32&&iv.size()==12&&tag.size()==16&&input.size()>=2&&input.size()<=514,"Invalid vault envelope");Alg alg;ok(BCryptOpenAlgorithmProvider(&alg.h,BCRYPT_AES_ALGORITHM,nullptr,0));ok(BCryptSetProperty(alg.h,BCRYPT_CHAINING_MODE,reinterpret_cast<PUCHAR>(const_cast<wchar_t*>(BCRYPT_CHAIN_MODE_GCM)),sizeof(BCRYPT_CHAIN_MODE_GCM),0));Key k;ok(BCryptGenerateSymmetricKey(alg.h,&k.h,nullptr,0,const_cast<PUCHAR>(key.data()),ULONG(key.size()),0));BCRYPT_AUTHENTICATED_CIPHER_MODE_INFO info;BCRYPT_INIT_AUTH_MODE_INFO(info);info.pbNonce=const_cast<PUCHAR>(iv.data());info.cbNonce=ULONG(iv.size());info.pbTag=tag.data();info.cbTag=ULONG(tag.size());info.pbAuthData=reinterpret_cast<PUCHAR>(const_cast<char*>(aad.data()));info.cbAuthData=ULONG(aad.size());Secret out(Bytes(input.size()));ULONG count{};ok(encrypt?BCryptEncrypt(k.h,const_cast<PUCHAR>(input.data()),ULONG(input.size()),&info,nullptr,0,out.bytes.data(),ULONG(out.bytes.size()),&count,0):BCryptDecrypt(k.h,const_cast<PUCHAR>(input.data()),ULONG(input.size()),&info,nullptr,0,out.bytes.data(),ULONG(out.bytes.size()),&count,0));require(count==input.size(),"Invalid vault plaintext");return out;
}
}
void rsaPublic(const Json& j){require(j.is_object()&&j.size()==3&&j.at("kty")=="RSA"&&j.at("e")=="AQAB","Invalid RSA key");const auto n=unb64url(j.at("n"));require(n.size()==256&&n[0]>=128,"RSA-2048 required");}
Bytes wrap(const Json& j,const Bytes& secret){require(secret.size()==32,"Invalid vault key");Alg alg;ok(BCryptOpenAlgorithmProvider(&alg.h,BCRYPT_RSA_ALGORITHM,nullptr,0));auto key=imported(j,alg.h);BCRYPT_OAEP_PADDING_INFO padding{BCRYPT_SHA256_ALGORITHM,nullptr,0};Bytes out(256);ULONG size{};ok(BCryptEncrypt(key.h,const_cast<PUCHAR>(secret.data()),ULONG(secret.size()),&padding,nullptr,0,out.data(),ULONG(out.size()),&size,BCRYPT_PAD_OAEP));require(size==256,"Invalid wrapped key");return out;}
Ephemeral::Ephemeral(){ok(BCryptOpenAlgorithmProvider(&algorithm_,BCRYPT_RSA_ALGORITHM,nullptr,0));try{ok(BCryptGenerateKeyPair(algorithm_,&key_,2048,0));ok(BCryptFinalizeKeyPair(key_,0));}catch(...){if(key_)BCryptDestroyKey(key_);BCryptCloseAlgorithmProvider(algorithm_,0);throw;}}
Ephemeral::~Ephemeral(){if(key_)BCryptDestroyKey(key_);if(algorithm_)BCryptCloseAlgorithmProvider(algorithm_,0);}
Json Ephemeral::jwk()const{ULONG size{};ok(BCryptExportKey(key_,nullptr,BCRYPT_RSAPUBLIC_BLOB,nullptr,0,&size,0));Bytes b(size);ok(BCryptExportKey(key_,nullptr,BCRYPT_RSAPUBLIC_BLOB,b.data(),size,&size,0));auto h=reinterpret_cast<BCRYPT_RSAKEY_BLOB*>(b.data());require(h->BitLength==2048&&h->cbModulus==256,"Invalid ephemeral RSA key");auto start=b.begin()+sizeof(*h);return {{"kty","RSA"},{"e",b64url(Bytes(start,start+h->cbPublicExp))},{"n",b64url(Bytes(start+h->cbPublicExp,b.end()))}};}
Secret Ephemeral::unwrap(const std::string& value)const{auto b=unb64url(value);require(b.size()==256,"Invalid release envelope");BCRYPT_OAEP_PADDING_INFO padding{BCRYPT_SHA256_ALGORITHM,nullptr,0};Secret result(Bytes(256));ULONG size{};ok(BCryptDecrypt(key_,b.data(),ULONG(b.size()),&padding,nullptr,0,result.bytes.data(),ULONG(result.bytes.size()),&size,BCRYPT_PAD_OAEP));require(size==32,"Invalid released key");SecureZeroMemory(result.bytes.data()+32,result.bytes.size()-32);result.bytes.resize(32);return result;}
Json seal(const Bytes& key,const std::wstring& password,const std::string& aad){require(!password.empty()&&password.size()<=256&&password.find(L'\0')==std::wstring::npos,"Invalid Windows password");Secret plain(Bytes(reinterpret_cast<const BYTE*>(password.data()),reinterpret_cast<const BYTE*>(password.data())+password.size()*2));auto iv=random(12);Bytes tag(16);auto encrypted=gcm(key,plain.bytes,iv,tag,aad,true);return {{"iv",b64url(iv)},{"tag",b64url(tag)},{"ciphertext",b64url(encrypted.bytes)}};}
Secret open(const Bytes& key,const Json& envelope,const std::string& aad){require(envelope.size()==3,"Invalid vault envelope");auto iv=unb64url(envelope.at("iv")),tag=unb64url(envelope.at("tag")),data=unb64url(envelope.at("ciphertext"));return gcm(key,data,iv,tag,aad,false);}
ULONG negotiatePackage(){HANDLE raw{};require(LsaConnectUntrusted(&raw)==0,"Windows authentication unavailable");LSA_STRING name{};char value[]="Negotiate";name.Buffer=value;name.Length=9;name.MaximumLength=10;ULONG id{};auto status=LsaLookupAuthenticationPackage(raw,&name,&id);LsaDeregisterLogonProcess(raw);require(status==0,"Windows Negotiate unavailable");return id;}
Bytes pack(const std::wstring& login,const Bytes& bytes,DWORD scenario){
  require((scenario==1||scenario==2)&&login.size()<=256&&bytes.size()>=2&&bytes.size()<=512&&bytes.size()%2==0,"Invalid credential input");
  std::wstring password(bytes.size()/2,L'\0');CopyMemory(password.data(),bytes.data(),bytes.size());struct Wipe{std::wstring& s;~Wipe(){SecureZeroMemory(s.data(),s.size()*2);}} wipe{password};require(password.find(L'\0')==std::wstring::npos,"Invalid password");
  if(login.starts_with(L"MicrosoftAccount\\")){
    DWORD flags=CRED_PACK_PROTECTED_CREDENTIALS|CRED_PACK_ID_PROVIDER_CREDENTIALS,count{};CredPackAuthenticationBufferW(flags,const_cast<LPWSTR>(login.c_str()),password.data(),nullptr,&count);require(GetLastError()==ERROR_INSUFFICIENT_BUFFER&&count>0&&count<8192,"Credential packing unavailable");Bytes buffer(count);if(!CredPackAuthenticationBufferW(flags,const_cast<LPWSTR>(login.c_str()),password.data(),buffer.data(),&count)){SecureZeroMemory(buffer.data(),buffer.size());throw std::runtime_error("Credential packing failed");}buffer.resize(count);return buffer;
  }
  // Local logon/unlock uses KERB_INTERACTIVE_UNLOCK_LOGON, including its LUID.
  const auto split=login.find(L'\\');require(split!=std::wstring::npos&&split>0&&split+1<login.size(),"Qualified local account required");auto domain=login.substr(0,split),user=login.substr(split+1);
  DWORD count{};CredProtectW(TRUE,password.data(),DWORD(password.size()+1),nullptr,&count,nullptr);require(GetLastError()==ERROR_INSUFFICIENT_BUFFER&&count>0&&count<2048,"Windows credential protection unavailable");std::wstring protectedPassword(count,L'\0');Wipe wipeProtected{protectedPassword};require(CredProtectW(TRUE,password.data(),DWORD(password.size()+1),protectedPassword.data(),&count,nullptr),"Windows credential protection failed");protectedPassword.resize(wcslen(protectedPassword.c_str()));
  Bytes packed(sizeof(KERB_INTERACTIVE_UNLOCK_LOGON)+(domain.size()+user.size()+protectedPassword.size())*2);auto header=reinterpret_cast<KERB_INTERACTIVE_UNLOCK_LOGON*>(packed.data());header->Logon.MessageType=scenario==1?KerbInteractiveLogon:KerbWorkstationUnlockLogon;size_t offset=sizeof(*header);
  auto append=[&](UNICODE_STRING& value,const std::wstring& text){value.Length=USHORT(text.size()*2);value.MaximumLength=value.Length;value.Buffer=reinterpret_cast<PWSTR>(offset);CopyMemory(packed.data()+offset,text.data(),value.Length);offset+=value.Length;};
  append(header->Logon.LogonDomainName,domain);append(header->Logon.UserName,user);append(header->Logon.Password,protectedPassword);return packed;
}
Json response(const std::string& token,const Json& key,const Json& request,const std::string& requestJws,bool enroll){require(epoch()<request.at("expiresAt").get<int64_t>(),"Expired vault response");auto p=verify(token,key,enroll?"vault-enrolled":"vault-response","password-unlock");auto decision=p.at("decision");require((decision=="approve"||decision=="deny")&&p.at("requestId")==request.at("requestId")&&p.at("challengeHash")==hash(requestJws)&&p.size()==(decision=="approve"?7:6),"Vault response binding mismatch");if(decision=="approve"){if(enroll)rsaPublic(p.at("phoneJwk"));else require(unb64url(p.at("wrappedKey")).size()==256,"Invalid key release");}return p;}
}
